### ISSUE TITLE
Tela de Registro

### ISSUE THREAD

**Issue by jemisonsantoos** [JemisonVidal/projIntegrador#5]
Objetivo: Implementar a tela de Registro

Layout: https://www.figma.com/file/l6UASzOqsEVXAfRKxb6eo8/projIntegrador

Campos:
- Nome
- Email
- Senha
- Confirmar Senha

Combobox:
- Candidata ou Empresa

Checkbox: 
- Concordo com os termos

Botões:
- Cadastrar
- Login

Links: Não haverá

Cenários:
- [x] Usuário cria conta se, nome,email,senha e confirmar senha estiverem validos;
- [x] Usuário vê mensagem de erro, se clicar em Cadastrar e nome não estiver preenchido;
- [x] Usuário vê mensagem de erro, se clicar em Cadastrar e email estiver invalido, se tem texto antes e depois do @ incluindo o ".com";
- [x] Usuário vê mensagem de erro, se clicar em Cadastrar e email ja estiver sendo usado
- [x] Usuário vê mensagem de erro, se clicar em Cadastrar e senha não combinar com confirmar senha.
- [x] Usuário vê mensagem de erro, se clicar em Cadastrar e senha estiver fraca(4 dígitos)
- [x] Usuário vê o botão Cadastrar desabilitado se não marcar o checkbok de termo;
- [x] Usuário é redirecionado quando clica no botão Login;
- [x] Usuário  é redirecionado para a pagina de login se conseguir cadastrar usuário;
- [x] Usuário vê mensagem de erro, se deixar o combobox desmarcado

**Comment by jemisonsantoos** [comment]
Liberado para code review
PR - #13

**Comment by AntonioGSC** [comment]
Review Aprovado
