### ISSUE TITLE
API Authenticate - Login

### ISSUE THREAD

**Issue by jemisonsantoos** [JemisonVidal/projIntegrador#7]
Objetivo: Implementar endpoint para autenticação do usuário

Endpoint: /v1/api/Authenticate

Campos(Body):
- Email: String 
- Password: String

Cenários:
- [x] API retorna as informações do usuáario + token, se o e-mail e password estiverem validos.
- [x] API retorna Email/Password inválidos, se o e-mail estiver invalido.
- [x] API retorna Email ou Password inválidos, se o password estiver invalido.
- [x] API retorna Usuário não cadastrado, se não localizar email

**Comment by ggwadera** [comment]
Implementado no endpoint `/v1/api/authenticate`

## Exemplo de request body

```js
{
  "email": "user@email.com",
  "password": "Password123"
}
```

## Exemplo de response

### Sucesso (STATUS 200 OK)
```js
{
  "user": {
    "name": "User Name",
    "email": "user@email.com",
    "type": "USER"
  },
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGVtYWlsLmNvbSIsImlhdCI6MTYwMDIxODgxOCwiZXhwIjo0MTkyMjE4ODE4fQ.LKyzG_sskkFQeMG422RBtLNaVA5t_dCPp-CITCbA67g"
}
```

### Falha (STATUS 401 Unauthorized)
